### PR TITLE
Switch to non-deprecated percent encoding methods (#34)

### PR DESCRIPTION
**Pull request by oysta**
Fix for #34

### CODE REVIEW

**Comment by tzm41** [comment]
@kylef Can we merge this please? This should fix the warning we are having for those of us who are using Mockingjay.

**Comment by sssilver** [comment]
@kylef any updates?

**Comment by kylef** [comment]
@sssilver Nope, there are no updates.

**Comment by sssilver** [comment]
@kylef There's an open pull request, is there a reason it isn't getting merged?

**Comment by kylef** [comment]
> Is there a reason it isn't getting merged?

It may get merged, once I have found sufficient time to review the pull request.

**Comment by kylef** [comment]
Thanks for the updates @oysta!

**Comment by oysta** [comment]
No problems @kylef! Thanks for this library—I'm happy to help out with other things if ever needed.

**Pull request merged**
